### ISSUE TITLE
Improve composer autoupdate behaviour

### ISSUE THREAD

**Issue by arzola** [pressbooks/composer-autoupdate-bedrock#73]
Our current plugins and themes has a github action step after running tests and all the build process that looks like this:

```
  - name: Trigger Bedrock Update
      if: (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/production')  && matrix.experimental == false
      uses: pressbooks/composer-autoupdate-bedrock@v2
      with:
        triggered-by: ${{ github.repository }}
        token: ${{ secrets.PAT_COMPOSER_UPDATE }}
        branch: ${{ github.ref }}
```
